SACBooking/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'',include('main.urls')),
    url(r'',include('booking.urls')),
    url(r'^admin/', admin.site.urls),
]

booking/urls.py
# - * - coding: utf-8 - * - 
from  django.conf.urls  import  include, url 
from  django.views.generic  import TemplateView
from booking import views

urlpatterns  = [
    url(r'^booking/',views.booking, name='booking'),
    url(r'^not_approved_yet/',views.not_approved, name='not_approved'),
    url(r'^my_bookings/',views.display_requests, name='my_bookings'),
    url(r'^all_bookings/',views.display_all_requests, name='all_bookings'),
    url(r'^delete/(?P<id>\d+)/', views.delete_request, name='delete_request'),
    url(r'^approved/(?P<id>\d+)/',views.approved, name='approved'),
    url(r'rejected/(?P<id>\d+)/', views.rejected, name='rejected'),
]

main/urls.py
from django.conf.urls import url
from main import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^registration/$',views.registration,name='registration'),
    url(r'^login/$',views.login_user, name='login'),
    url(r'^logout/$', views.logout_user,name='logout'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^account_verified/$',views.account_verified,name='account_verified'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

]

booking/models.py
from django.contrib.auth.models import User
from django.db import models

from main.models import Profile


# Create your models here.
class Room(models.Model):
    Room_no = models.CharField(max_length=10)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Booking(models.Model):
    Room_no = models.ForeignKey(Room, on_delete=models.CASCADE)
    Booking_start  = models.DateTimeField()
    Booking_end = models.DateTimeField()
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)  
    Approved = models.BooleanField(default=False)
    Rejected = models.BooleanField(default=False)

    class Meta:
        ordering = ['Booking_start']


    def __str__(self):
        return "%s is to be Booked from %s to %s " %(self.Room_no, self.Booking_start , self.Booking_end)

main/models.py
from __future__ import unicode_literals


from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db import models
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=254)
    bio = models.TextField(max_length=500, blank=True)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

booking/forms.py
from django import forms
from booking import models

class BookingForm(forms.ModelForm):

    class Meta:
        model = models.Booking
        fields = ('Room_no', 'Booking_start', 'Booking_end', )

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from main import models

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

booking/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.template.loader import render_to_string

from datetime import datetime
import dateutil.parser 
import pytz

from booking.forms import BookingForm
from booking.models import *
# Create your views here.


def booking(request):
    form = BookingForm()
    wrong_date_selection = False
    clash = False
    request_made = False
    if request.POST:
        form = BookingForm(request.POST)
        utc = pytz.UTC
        room_no = request.POST['Room_no']
        booking_start = utc.localize(dateutil.parser.parse(request.POST['Booking_start']))
        booking_end = utc.localize(dateutil.parser.parse(request.POST['Booking_end']))

        print(room_no, booking_start, booking_end)
        
        if (booking_start > booking_end) or (booking_start < utc.localize(datetime.now()) or booking_end < utc.localize(datetime.now())):
            wrong_date_selection = True
            print("Wrong Date Selected.")
            return render(request,'booking.html',{'verified':request.user.profile.email_confirmed, 'wrong_date_selection':wrong_date_selection, 'form' : form })
        else:
            booking  = Booking(Room_no=Room.objects.get(pk=room_no), Booking_start=booking_start, Booking_end=booking_end, user=request.user.profile)
            booking.save()
            request_made = True
            return render(request,'booking.html',{'verified':request.user.profile.email_confirmed,'booking':booking, 'form' : form, 'request_made':request_made })
    else:
        print("Inside Booking")        
        return render(request,'booking.html',{'verified':request.user.profile.email_confirmed,'form' : form, 'clash': clash, 'wrong_date_selection':wrong_date_selection})

def approved(request):
    return render(request,'approved.html')

def not_approved(request):
    return render(request,'not_approved.html')

def display_requests(request):
    if request.user.is_staff:
        my_bookings = Booking.objects.all()
    else:
        my_bookings = Booking.objects.filter(user=request.user.profile)
    return render(request,'display_my_bookings.html',{'my_bookings':my_bookings, 'verified':request.user.profile.email_confirmed})

def delete_request(request, id):
    booking = Booking.objects.get(id=id)
    if request.user.is_staff:
        from_mail = settings.EMAIL_HOST_USER
        to_list = [ booking.user.user.email ]
        subject = "Your Booking is Deleted."
        message = render_to_string('booking_deleted.html', {
                    'user': booking.user,
                })
        print(from_mail, to_list, subject, message)
        send_mail(subject,message, from_mail, to_list, fail_silently=True)
    booking.delete()
    return HttpResponseRedirect('/my_bookings/')

def approved(request, id):
    booking = Booking.objects.get(id=id)
    all_bookings = Booking.objects.all()
    for book in Booking.objects.filter(Room_no=booking.Room_no,Approved=True).exclude():
        if (booking.Booking_start >= book.Booking_start and booking.Booking_start <= book.Booking_end ) or ( booking.Booking_end >= book.Booking_start and booking.Booking_end <= book.Booking_end ) or(booking.Booking_start < book.Booking_start and booking.Booking_end > book.Booking_end):
            if booking.id == book.id:
                continue
            clash = True
            return render(request,'display_all_bookings.html',{'verified':request.user.profile.email_confirmed, 'clash_booking':booking, 'clash': clash, 'all_bookings' : all_bookings })
    booking.Approved = True
    booking.Rejected = False
    if request.user.is_staff:
        from_mail = settings.EMAIL_HOST_USER
        to_list = [ booking.user.user.email ]
        subject = "Your Booking is Approved."
        message = render_to_string('booking_approved.html', {
                    'user': booking.user,
                })
        print(from_mail, to_list, subject, message)
        send_mail(subject,message, from_mail, to_list, fail_silently=True)
    booking.save()
    return HttpResponseRedirect('/my_bookings/')

def rejected(request, id):
    booking = Booking.objects.get(id=id)
    booking.Rejected = True
    booking.Approved = False
    if request.user.is_staff:
        from_mail = settings.EMAIL_HOST_USER
        to_list = [ booking.user.user.email ]
        subject = "Your Booking is Rejected."
        message = render_to_string('booking_rejected.html', {
                    'user': booking.user,
                })
        print(from_mail, to_list, subject, message)
        send_mail(subject,message, from_mail, to_list, fail_silently=True)
    booking.save()
    return HttpResponseRedirect('/my_bookings/')

def display_all_requests(request):
    if request.user.is_staff:
        all_bookings = Booking.objects.all()
    else:
        all_bookings = Booking.objects.filter(Approved=True)
    return render(request,'display_all_bookings.html',{'all_bookings':all_bookings, 'verified':request.user.profile.email_confirmed})

main/views.py
from django.conf import settings
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
# from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from datetime import datetime
import dateutil.parser 
import pytz

from booking.forms import BookingForm
from main.forms import SignUpForm
from main.tokens import account_verification_token
from main.models import *


@login_required
def home(request):
    # login(request, user)
    return render(request, 'home.html')


def login_user(request):
    login_failed = False
    logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            login_failed = False
            form = BookingForm()
            if user.is_active:
                login(request, user)
                print("User is Not none and active as well.")
            else:
                login(request, user)
                print("User is Not None but not Active.")

            return HttpResponseRedirect('/booking/',{'verified':request.user.profile.email_confirmed, 'login_failed':login_failed, 'form' : form })
        else:
            login_failed = True
            print("User is None")
    return render(request,'home.html',{ 'login_failed':login_failed })

def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')

def registration(request):
    logout(request)
    
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            USER = form.save(commit=True)
            USER.is_active = True
            USER.save()
            from_mail = settings.EMAIL_HOST_USER
            to_list = [settings.GSEC_EMAIL]

            current_site = get_current_site(request)
            subject = 'Approve '+ USER.username +' SACRoom Booking Account'
            message = render_to_string('account_verification_email.html', {
                'user': USER,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(USER.pk)),
                'token': account_verification_token.make_token(USER),
            })
            login(request, USER)
            send_mail(subject,message, from_mail, to_list, fail_silently=True)

            return redirect('account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'registration.html', {'form': form})

def account_activation_sent(request):
    if request.user.is_authenticated:
        return render(request, 'account_activation_sent.html')
    else:
        return redirect('home')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_verification_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        from_mail = settings.EMAIL_HOST_USER
        to_list = [user.email]
        subject = 'SAC Room Booking Account Verified.'
        message = render_to_string('account_verified_email.html', {
                'user': user,
            })
        send_mail(subject,message, from_mail, to_list, fail_silently=True)
        return redirect('account_verified')
    else:
        return render(request, 'account_activation_invalid.html')

def account_verified(request):
    return render(request,'account_verified.html')

main/templates/account_activation_sent.html
{% extends 'base.html' %}

{% block registration %}

{% if user.is_authenticated  %}
<div class="row text-left">
  <div class="col">
    <a href="{% url 'logout' %}" class="btn btn-primary">logout</a>
  </div>
</div>
{% endif %}
<div class="row text-center">
  <div class="col">
   <p>Please Wait for General Secretary to Verify your Account.<br>If its 'URGENT' or
     Its been a long time, your Account verification is pending, please Contact the General Secretary.</p>
  </div>
</div>
{% endblock %}

main/templates/account_verification_email.html
{% autoescape off %}
Hi General Secrectary,

Person With Following Details want to Register with SAC Room Booking Portal.
UserName : {{ user.username }}
EmailID : {{ user.email }}

To Verify the account, Click on this link:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}

Note: By clicking On this link, you verify that the details above mentioned are correct and this Person can access the SAC Room Booking Portal.
If you find any discrepencies, please contact the person by sending mail to {{ user.email }}.

{% endautoescape %}

main/templates/account_verified.html
{% extends 'base.html' %}

{% block registration %}
<div class="row text-center">
    <div class="col">
        <p> Thanks for Verifying  Account.</p>
    </div>
</div>
{% endblock %}

main/templates/account_verified_email.html
{% autoescape off %}
Hi {{ user.username }},

Your Account on SAC Room Booking Portal is Verified by the General Secretary.

Now, you can use your account to book Rooms.
Your Email : {{ user.email }}.

{% endautoescape %}

main/templates/approved.html
{% extends 'home.html' %}

{% block approved %}
<div class="row text-center">
   <p>Your Request is approved by the SAC Admin.<br>
        and your event is booked.
   </p>
</div>

{% endblock %}

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}SAC Room Booking Portal{% endblock %}</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.0/css/mdb.min.css" rel="stylesheet">


<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.0/js/mdb.min.js"></script>
            

  </head>
  <body>
    <header class="text-center" style="background:rgba(52, 137, 163,220)">
        <div class="text-center" style="margin-right:60px;">
      <h1 style="padding-top:10px; margin-top:10px;">SAC Room Booking Portal</h1>
      {% if not user.is_authenticated %}
      
        <a href="{% url 'login' %}" class="btn btn-primary">login</a>  <a href="{% url 'registration' %}" class="btn btn-info">signup</a>
      </div>
      {% endif %}
      <hr>
    </header>
    <main>
        <div class="container-fluid">
            {% block home %}
            {% endblock %}
            {% block registration %}
            {% endblock %}
        </div>
    </main>
  </body>
</html>

main/templates/booking.html
{% extends 'home.html' %}

{% block booking_form %}
<div class="row">
    <div class="col">
        <form  method="POST" class="post-form" action="/booking/"> {% csrf_token %}
            <p> {{ form.Room_no.label_tag }}
                {{ form.Room_no }}</p>
            <p><label for="id_Booking_start">Booking start:</label> <input type="datetime-local" name="Booking_start" id="id_Booking_start" required=""></p>
            <p><label for="id_Booking_end">Booking end:</label> <input type="datetime-local" name="Booking_end" id="id_Booking_end" required=""></p>
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </div>
</div>
<div class="row text-center">
    <div class="col">
            {% if wrong_date_selection %}
            <p style="color:  red;">Bad Date Selection.</p>
            {% endif %}
            {%  if clash %}
            <p style="color: red;">
                Your Booking Dates are Clashing with {{ booking.user.profile }} 's Event.<br> Please Select Other Dates.
            </p>
            {% endif %}
            {% if request_made %}
            <p style="color:  green;">
                Your Request has been made successfully. Please wait for SAC Admin/GSEC to approve your Request.
            </p>
            {% endif %}
    </div>
</div>

{% endblock %}

main/templates/booking_deleted.html
{% autoescape off %}
Hi {{ user }},

Your Booking on SAC Room Booking Portal is Cancelled by the SAC Admin/General Secretary.
Sorry, for the inconvienence caused.

{% endautoescape %}

main/templates/booking_rejected.html
{% autoescape off %}
Hi {{ user }},

Your Booking on SAC Room Booking Portal is Rejected by the SAC Admin/General Secretary.
Sorry, for the inconvienence caused.

Regards,
Insti Sysad.
{% endautoescape %}

main/templates/display_my_bookings.html
{% extends 'home.html' %}
{% block display_requests %}
<div class="container">
        {% for booking in my_bookings %}
        <div class="row" style="
                            border: solid;
                            border-color:  wheat;
                            padding-top: 10px;">
            <div class="col-md-9">
                    {% if user.is_staff %}
                <p>Requested By: {{ booking.user }}</p>
                {% endif %}
                <p>Room: {{ booking.Room_no }}</p>
                <p>From:  {{ booking.Booking_start }}</p>
                <p>To: {{ booking.Booking_end}}</p>
                <p>Status: {% if booking.Approved %} Approved {% elif booking.Rejected %} Rejected {% else %} Pending {% endif %}</p>
            </div>
            {% if user.is_staff %}
            <div class="col-md-1">
                    <a href="/approved/{{ booking.id }}" class="btn btn-primary" name="approved" style="margin-top: 48px;"><i class="material-icons">done</i></a>
                </div>
                <div class="col-md-1">
                        <a href="/rejected/{{ booking.id }}" class="btn btn-secondary" name="rejected" style="margin-top: 48px;"><i class="material-icons">clear</i></a>
                    </div>
            {% endif %}
            <div class="col-md-1">
                <a href="/delete/{{ booking.id }}" class="btn btn-danger" name="delete" style="margin-top: 48px;"><i class="material-icons">delete</i></a>
            </div>
        </div>
        {% empty %}
        <div class="row text-center">
            <div class="col">
                <p> NO, Bookings.</p>
                {% if not user.is_staff %}
                <a href="/booking/" class="btn btn-success">Book Now</a>
                {% endif %}
            </div>
        </div>  
        {% endfor %}
    
</div>
{% endblock %}

main/templates/home.html
{% extends 'base.html' %}

{% block home %}
<div class="row">
    <div class="col text-left">
        {% if user.is_authenticated  %}
            <a href="{% url 'logout' %}" name="logout_buuton" class="btn btn-primary">logout</a>
    </div>
    <div class="col-md-3 text-right">
            <a href="{% url 'all_bookings'%}" class="btn btn-danger" role="button">All Bookings</a>
    </div>
    {% if not user.is_staff %}
    <div class="col-md-3 text-right">
            <a href="{% url 'my_bookings'%}" class="btn btn-deep-orange" role="button">My Bookings</a>
    </div>
    {% endif %}
</div>

    {% if  verified  %}
<div class="row text-center">
    <div class="col">
        <h2>Welcome, {{ user.username }}</h2>
        <p>Your Account is Verified by the GSEC.</p>

        {% block booking_form %}
        {% endblock %}

        {% block display_requests %}
        {% endblock %}
    </div>
</div>
    {% else %}
<div class="row text-center">
    <div class="col">
            <p> Your Account's Verification is stil pending with GSEC.</p>
        </div>
</div>
    {% endif %}
{% else %}
<div id="login" class="row text-center">
    <div class="col">
        <form class="form-horizontal" name="LoginForm" action="/login/" method="post">
        {% csrf_token %}
            <div class="control-group">
                <label class="control-label" for="username">Username</label>
                <div class="controls">
                    <input type="text" id="username" name="username"  placeholder="Username">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="password">Password</label>
                <div class="controls">
                    <input type="password" name="password" id="password" placeholder="Password">
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn">Login</button>
                </div>
            </div>
            {% if login_failed %}
            <p>Login Failed !!! <p>
        {% endif%}
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

main/templates/login.html
{% extends "base.html" %}
{% block content %}
 {% if not user.is_authenticated %}
    <div id="login" class="row text-center">
        <form class="form-horizontal" name="LoginForm" action="" method="post">
        {% csrf_token %}
        <div class="control-group">
            <label class="control-label" for="username">Username</label>
            <div class="controls">
                <input type="text" id="username" name="username"  placeholder="Username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="password">Password</label>
            <div class="controls">
                <input type="password" name="password" id="password" placeholder="Password">
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Login</button>
            </div>
        </div>
        {% if login_failed %}
          <p>Login Failed !!! <p>
        {% endif%}
        </form>
    </div>
    {% else %}
    {% endif %}
{% endblock %}

main/templates/not_approved.html
{% extends 'home.html' %}

{% block not_approved %}
<div class="row text-center">
   <p>Please Wait for SAC Admin to Approve your Request.<br>If its 'URGENT' or
     Its been a long time, your request is pending, please Contact the SAC Admin/General Secretary.</p>
</div>
{% endblock %}

main/templates/registration.html
{% extends 'base.html' %}

{% block registration %}
<div class="row text-center">
  <div class="col">
        <h2>Sign up</h2>
  </div>
</div>
<div class="row text-center" >
  <div class="col">
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
  </div>
</div>
{% endblock %}